spring.application.name=jwt-deneme

server.port=8082


spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect= org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql= true

spring.datasource.url= jdbc:mysql://localhost:3306/jwt_deneme?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username= ekrem
spring.datasource.password= 1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
